### ISSUE TITLE
Httpbeast integration

### ISSUE THREAD

**Issue by ducdetronquito** [ducdetronquito/phoon#28]
Is it worth it to be able to run on top of [Httpbeast](https://github.com/dom96/httpbeast) or is the standard http server good enough ?

Any insight on the subject is welcomed :)

**Comment by Willyboar** [comment]
Httpbeast doesn't seem like a good option right now because the owner seems to left the community. You can probably try httpx - a fork of httpbeast that working on windows or the new mummy server who has a similar api with asynchttpserver.

**Comment by ducdetronquito** [comment]
Hey @Willyboar

Thanks for the advice, I follow mummy's development too and I find it quiet cool: I can't put much time into it these year unfortunately as I repair an old house, so the project will be dormant.

Have a nice day !
