### ISSUE TITLE
Error: ambiguous identifier: 'Callback'

### ISSUE THREAD

**Issue by mitjafelicijan** [ducdetronquito/phoon#33]
After installing `phoon` with `nimble install phoon` I created `main.nim` file with the following contents.

```nim
import phoon

var app = new App

app.get("/",
    proc (ctx: Context) {.async.} =
        ctx.response.body("I am a boring home page")

app.serve(8080)
```

When I try to run the file with the `nim c --run main.nim` I get the following error:

```
12:55:59 m@khan yapyap →nim c -d:danger --run main.nim
Hint: used config file '/home/m/.choosenim/toolchains/nim-1.6.0/config/nim.cfg' [Conf]
Hint: used config file '/home/m/.choosenim/toolchains/nim-1.6.0/config/config.nims' [Conf]
...............................................................................................................................
/home/m/.nimble/pkgs/phoon-0.1.0/phoon.nim(13, 32) Error: ambiguous identifier: 'Callback' -- use one of the following:
  asyncdispatch.Callback: Callback
  route.Callback: Callback
```

My nim version

```
12:54:47 m@khan ~ → nim --version
Nim Compiler Version 1.6.0 [Linux: amd64]
Compiled at 2021-10-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 727c6378d2464090564dbcd9bc8b9ac648467e38
active boot switches: -d:release
```

**Comment by ducdetronquito** [comment]
Hi @mitjafelicijan !

I do not work on phoon these days, so I won't promise I will be able to fix this anytime soon.

However, I recommend you to check out [prologue](https://github.com/planety/prologue) if you look for a more mature web framework, or [httpbeast](https://github.com/dom96/httpbeast) if you want a raw HTTP server and build your own framework around it.

Have a nice sunday :)
