### ISSUE TITLE
How can I update to 0.3

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ducdetronquito/phoon#36]
nimble install phoon@0.3.0
Downloading https://github.com/ducdetronquito/phoon using git
       Tip: 3 messages have been suppressed, use --verbose to show them.
     Error: Downloaded package's version does not satisfy requested version range: wanted 0.3.0 got 0.2.0.

**Comment by ducdetronquito** [comment]
Hi @Yakumo-Yukari !

My bad, I forgot to bump the version number in my nimble file.

You should be able to download phoon 0.3.0 now !
