### ISSUE TITLE
I'd like to see a prompt for a successful start and browse for addresses and ports, currently there is no prompt for a successful start

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ducdetronquito/phoon#37]
![1](https://user-images.githubusercontent.com/12076232/200266706-1f34d5de-6775-470b-9613-e8dabe315ede.png)

I'd like to see a prompt for a successful start and browse for addresses and ports, currently there is no prompt for a successful start

**Comment by ducdetronquito** [comment]
The 0.4.0 is available, which logs when the server starts.
Careful, I changed the `serve` function signature so the address must be provided before the port.

In your example, it should be written:

```nim
app.serve(port=2333)
```

Enjoy :)
